### ISSUE TITLE
for loop in weighted_graph.py

### ISSUE THREAD

**Issue by RavenHex1296** [anton-perez/graph#7]
In your calc_shortest_path method for the WeightedGraph class, your for loop can be redone differently. Instead of doing for edge in self.edges, you can do for (a, b) in self.edges. That way, you dont have to do node_a = self.nodes[edge[0]] and node_b = self.nodes[edge[1]]. Of course, this is just a suggestion, so if you prefer your way of doing it, feel free to ignore this.

**Comment by anton-perez** [comment]
Thanks, I'll keep that in mind moving forward.
